# Site settings
title: Walk For Sean
email:
description: > # this means to ignore newlines until "baseurl:"
  Walk For Sean
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://walkforsean.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown
